version: '3.8'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./config/:/usr/config/app/

    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    networks:
      - web
volumes:
  postgres_data:


networks:
  web:
    driver: bridge