# Generated by Django 5.0.4 on 2024-06-15 18:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='user_avatars/default.jpg', upload_to=users.models.user_avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
