# Generated by Django 5.0.3 on 2024-03-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('P', 'private'), ('G', 'group')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'audio'), ('V', 'video'), ('T', 'text'), ('I', 'image'), ('F', 'file')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSettingsHasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'admin'), ('O', 'owner'), ('D', 'default')], max_length=7)),
                ('group_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.groupsettings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='user',
            field=models.ManyToManyField(through='chats.GroupSettingsHasUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.BooleanField(default=False)),
                ('text_content', models.TextField()),
                ('audio_content', models.FileField(upload_to='')),
                ('video_content', models.FileField(upload_to='')),
                ('file_content', models.FileField(upload_to='')),
                ('img_content', models.ImageField(upload_to='')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chats.messagecontent')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_content',
            field=models.ManyToManyField(through='chats.Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
