# Generated by Django 5.0.4 on 2024-04-19 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_content',
            field=models.ManyToManyField(related_name='chat', through='chats.Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
