# Generated by Django 5.0.4 on 2024-05-30 12:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_chat_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_content',
        ),
        migrations.AddField(
            model_name='chat',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 30, 15, 24, 15, 340056)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_settings', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='user',
            field=models.ManyToManyField(related_name='group_settings', through='chats.GroupSettingsHasUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsettingshasuser',
            name='group_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings_in_group', to='chats.groupsettings'),
        ),
        migrations.AlterField(
            model_name='groupsettingshasuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings_in_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
