# Generated by Django 5.0.4 on 2024-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_chat_chat_content_chat_current_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsettings',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
