# Generated by Django 5.0.4 on 2024-06-05 15:53

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_groupsettings_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsettings',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='avatar',
            field=models.ImageField(upload_to=chats.models.group_avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_content',
            field=models.FileField(upload_to=chats.models.message_file_content_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_content',
            field=models.FileField(upload_to=chats.models.message_file_content_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='img_content',
            field=models.ImageField(upload_to=chats.models.message_file_content_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_content',
            field=models.FileField(upload_to=chats.models.message_file_content_upload_path),
        ),
    ]
