# Generated by Django 5.0.4 on 2024-06-07 13:55

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_rename_user_groupsettings_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsettings',
            name='avatar',
            field=models.ImageField(default='chat_avatars/default.jpg', upload_to=chats.models.group_avatar_upload_path),
        ),
    ]
