# Generated by Django 5.0.4 on 2024-06-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_usertochat_chat_new_current_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='current_users',
        ),
    ]
