# Generated by Django 5.0.4 on 2024-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_groupsettings_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
