# Generated by Django 5.0.4 on 2024-07-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_message_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply'
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chats.message'),
        ),
    ]
